services:
  app:
    build: ./app
    restart: unless-stopped
    ports:
      - 3125:3000
    volumes:
      - ${APP_DATA_DIR}/data:/data
    depends_on:
      - db
    environment:
      - NODE_ENV=production

  db:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/db:/data/db